name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "ReadDemo/**"
      - ".github/workflows/azure-static-web-apps-delightful-cliff-02545aa03.yml"

  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - "ReadDemo/**"
      - ".github/workflows/azure-static-web-apps-delightful-cliff-02545aa03.yml"

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
          include-prerelease: true
          
      - name: Client Build
        run: dotnet publish ./ReadDemo/Client/Client.csproj --output ./ClientDist

      - name: Api Build
        run: dotnet publish ./ReadDemo/Api/Api.csproj --output ./ApiDist    
        
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_CLIFF_02545AA03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "ClientDist/wwwroot" # App source code path
          api_location: "ApiDist" # Api source code path - optional
          skip_app_build: true
          skip_api_build: true
          ###### End of Repository/Build Configurations ######



      # - name: Build And Deploy
      #   id: builddeploy
      #   uses: Azure/static-web-apps-deploy@v1
      #   with:
      #     azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_CLIFF_02545AA03 }}
      #     repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
      #     action: "upload"
      #     ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
      #     # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      #     app_location: "ReadDemo/Client" # App source code path
      #     api_location: "ReadDemo/Api" # Api source code path - optional
      #     output_location: "wwwroot" # Built app content directory - optional
      #     ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_CLIFF_02545AA03 }}
          action: "close"
